### ISSUE TITLE
920 text editor gone from Google Play? 

### ISSUE THREAD

**Issue by andrixnet** [jecelyin/920-Text-Editor-old#26]
Hi, 

I've had this editor installed on my devices for some time now and used it with great success. 
I just received a new smartphone and tried to install it, but could not find it on the Play store anymore.

**Comment by Gitoffthelawn** [comment]
I've noticed this too.  There is version on F-Droid, but it's not the current version.

Anyone know what's going on?

**Comment by hit1205** [comment]
I also noticed it. There are some apk files in [repository](https://github.com/jecelyin/920-Text-Editor/tree/master/apk), not sure it's last version or not.

**Comment by Gitoffthelawn** [comment]
I believe version 13.7.18 was the last version available on Google Play.  I haven't done a bitwise comparison to determine if it's the same as the version 13.7.18 here on github.

As of this writing, version 12.11.23 is the latest of F-Droid.

**Comment by timofonic** [comment]
Are there plans to resucitate this project? Any fork or alternative? The features are really interesting.

**Comment by HR** [comment]
Yes

**Comment by Gitoffthelawn** [comment]
@HR Great!  Thanks!

**Comment by Gitoffthelawn** [comment]
The newer repo (https://github.com/jecelyin/920-text-editor-v2/) doesn't have an issue reporter... so I'll ask here: Is the newer version going to be added to F-Droid?

TIA
